### ISSUE TITLE
Cadastro do Reclamante

### ISSUE THREAD

**Issue by huandersonlima** [ThierryMatheus/ProjetoPilotoPEP2#11]
**Como** Reclamante,
**Quero** me cadastrar no sistema
**Para** criar minhas próprias denúncias e/ou interagir com as demais.

- [x] Implementar backend do cadastro;
- [x] Criar a view de cadastro do Reclamante;
- [x] Testar a funcionalidade.

**Comment by Gjss333** [comment]
Issues do cadastro do reclamante finalizadas

@huandersonlima  obrigado pela ajuda man
